"""Tool generator tool — intelligent tool creation and management.

1:1 port of SkyworkAI's ToolGeneratorTool from src/tool/workflow_tools/tool_generator.py.
Simplified for Orbiter: no TCP/registry, generates and evaluates tools via LLM.
"""

from __future__ import annotations

import ast
import json
import logging
import os
from typing import Any

from pydantic import BaseModel, Field

from orbiter.tool import Tool
from orbiter.types import SystemMessage, UserMessage

from ..llm_utils import call_llm

logger = logging.getLogger("deepagent")


class ToolSpecification(BaseModel):
    """Tool specification extracted from task analysis."""
    tool_name: str = Field(description="Name of the tool to create")
    description: str = Field(description="Functional description of the tool")
    parameters: dict[str, Any] = Field(description="Parameter schema for the tool")
    implementation_plan: str = Field(description="Plan for implementing the tool")


class ToolEvaluation(BaseModel):
    """Response format for evaluating tool correctness."""
    is_valid: bool = Field(description="Whether the tool implementation is valid")
    errors: list[str] = Field(default_factory=list, description="List of errors found")
    warnings: list[str] = Field(default_factory=list, description="List of warnings found")
    reasoning: str = Field(description="Brief explanation of the evaluation result")


class ToolTestCase(BaseModel):
    """A single test case for a generated tool."""
    name: str = Field(description="Short name for the test case")
    input: dict[str, Any] = Field(description="Input arguments to pass to the tool")
    expected_behavior: str = Field(description="Description of what success looks like")


class ToolTestSuite(BaseModel):
    """Collection of test cases generated by LLM."""
    test_cases: list[ToolTestCase] = Field(description="List of test cases")


_TOOL_GENERATOR_DESCRIPTION = """Tool generator tool that creates new tools dynamically.
This tool will:
1. Analyze task requirements and extract tool specifications
2. Generate new tool implementations via LLM
3. Evaluate newly created tools for correctness
4. Save validated tools to disk

Args:
- task (str): The task to complete.
- tool_name (Optional[str]): Optional explicit tool name.
- description (Optional[str]): Optional explicit tool description.

Example: {"name": "tool_generator", "args": {"task": "Create a tool that summarizes text"}}.
"""


class ToolGeneratorTool(Tool):
    """Generate, evaluate, and save new tools dynamically.

    1:1 port of SkyworkAI's ToolGeneratorTool, simplified for Orbiter (no TCP registry).
    """

    def __init__(
        self,
        *,
        model: str = "openai:gpt-4o-mini",
        base_dir: str = "deepagent_output/tool_generator",
    ) -> None:
        self.name = "tool_generator"
        self.description = _TOOL_GENERATOR_DESCRIPTION
        self.parameters = {
            "type": "object",
            "properties": {
                "task": {
                    "type": "string",
                    "description": "The task description that requires a tool.",
                },
                "tool_name": {
                    "type": "string",
                    "description": "Optional explicit tool name.",
                },
                "description": {
                    "type": "string",
                    "description": "Optional explicit tool description.",
                },
            },
            "required": ["task"],
        }
        self._model = model
        self._base_dir = base_dir
        os.makedirs(self._base_dir, exist_ok=True)

    async def execute(self, **kwargs: Any) -> str:
        """Execute tool generation workflow.

        Args:
            task: The task description that requires a tool.
            tool_name: Optional explicit tool name.
            description: Optional explicit tool description.

        Returns:
            Generation result or error message.
        """
        task: str = kwargs.get("task", "")
        tool_name: str | None = kwargs.get("tool_name")
        description: str | None = kwargs.get("description")

        if not task:
            return "Error: No task provided."

        try:
            logger.info(f"Starting tool generation for task: {task}")

            # Step 1: Task Analysis
            logger.info("Step 1: Analyzing task requirements...")
            tool_spec = await self._analyze_task(task, tool_name, description)
            logger.info(f"Tool specification: {tool_spec.tool_name}")

            # Step 2: Generate tool code
            logger.info("Step 2: Generating tool implementation...")
            tool_code = await self._generate_tool_code(tool_spec)

            # Step 3: Evaluate
            logger.info("Step 3: Evaluating generated tool...")
            evaluation = self._evaluate_tool(tool_spec, tool_code)

            if not evaluation.is_valid:
                return (
                    f"Tool generation failed evaluation: {evaluation.reasoning}. "
                    f"Errors: {', '.join(evaluation.errors)}"
                )

            # Step 4: Save to disk
            logger.info("Step 4: Saving tool to disk...")
            file_path = os.path.join(self._base_dir, f"{tool_spec.tool_name}.py")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(tool_code)

            return (
                f"Successfully generated tool '{tool_spec.tool_name}'.\n"
                f"Description: {tool_spec.description}\n"
                f"Saved to: {file_path}"
            )

        except Exception as e:
            logger.error(f"Error in tool generation: {e}")
            return f"Error during tool generation: {e}"

    async def _analyze_task(
        self, task: str, tool_name: str | None, description: str | None
    ) -> ToolSpecification:
        """Analyze task to extract tool specifications."""
        system_prompt = (
            "You are an expert at analyzing tasks and extracting tool specifications. "
            "Analyze the given task and determine what tool is needed."
        )

        user_prompt = f"""Analyze the following task and extract tool specifications:

Task: {task}

{"Tool name (if specified): " + tool_name if tool_name else ""}
{"Tool description (if specified): " + description if description else ""}

Extract the following information:
1. Tool name: A clear, descriptive name for the tool (use snake_case)
2. Description: A detailed functional description of what the tool does
3. Parameters: A JSON schema describing the tool's input parameters
4. Implementation plan: A brief plan for implementing the tool"""

        messages = [
            SystemMessage(content=system_prompt),
            UserMessage(content=user_prompt),
        ]

        response = await call_llm(
            model=self._model,
            messages=messages,
            response_format=ToolSpecification,
        )

        if response.parsed_model is not None:
            return response.parsed_model

        # Fallback
        return ToolSpecification(
            tool_name=tool_name or "generated_tool",
            description=description or task,
            parameters={"type": "object", "properties": {}, "required": []},
            implementation_plan="Generate tool implementation based on task requirements",
        )

    async def _generate_tool_code(self, spec: ToolSpecification) -> str:
        """Generate tool implementation code."""
        system_prompt = (
            "You are an expert Python developer specializing in creating tools for AI agents. "
            "Generate complete, working tool implementations."
        )

        user_prompt = f"""Generate a complete Python tool implementation for:

Tool Name: {spec.tool_name}
Description: {spec.description}
Parameters: {json.dumps(spec.parameters, indent=2)}
Implementation Plan: {spec.implementation_plan}

The tool must follow this pattern:

from orbiter.tool import Tool
from typing import Any

class MyTool(Tool):
    def __init__(self):
        self.name = "{spec.tool_name}"
        self.description = "{spec.description}"
        self.parameters = {json.dumps(spec.parameters)}

    async def execute(self, **kwargs: Any) -> str:
        # Implementation here
        pass

Return ONLY the code, no explanations or markdown formatting."""

        messages = [
            SystemMessage(content=system_prompt),
            UserMessage(content=user_prompt),
        ]

        response = await call_llm(model=self._model, messages=messages)
        code = response.message.strip()
        # Strip markdown fences if present
        if code.startswith("```"):
            lines = code.split("\n")
            if lines[0].startswith("```"):
                lines = lines[1:]
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            code = "\n".join(lines)
        return code

    def _evaluate_tool(self, spec: ToolSpecification, tool_code: str) -> ToolEvaluation:
        """Evaluate the generated tool for correctness."""
        errors: list[str] = []
        warnings: list[str] = []

        # Check syntax
        try:
            ast.parse(tool_code)
        except SyntaxError as e:
            errors.append(f"Syntax error: {e}")

        # Check for required patterns
        if "class " not in tool_code:
            errors.append("No class definition found in tool code")
        if "async def execute" not in tool_code:
            errors.append("Missing 'async def execute' method")
        if "Tool" not in tool_code:
            warnings.append("Tool base class not referenced")

        if errors:
            return ToolEvaluation(
                is_valid=False,
                errors=errors,
                warnings=warnings,
                reasoning=f"Tool validation failed with {len(errors)} error(s)",
            )

        return ToolEvaluation(
            is_valid=True,
            errors=errors,
            warnings=warnings,
            reasoning="Tool passed basic validation checks",
        )
